### ISSUE TITLE
Exception when loading objects with nested dataclasses

### ISSUE THREAD

**Issue by lumisota** [jacebrowning/datafiles#163]
The following (assuming ```samples``` is empty beforehand):

```
from datafiles import datafile, Missing
from dataclasses import dataclass

@dataclass
class Name:
    value : str


@datafile("samples/{self.key}.yml")
@dataclass
class Sample:

    key: int
    name: Name
    value: float = 0.0
    

sample = Sample(42, Name("Widget"))

sample2 = Sample(42, Missing)
```

results in an exception:

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    sample2 = Sample(42, Missing)
  File "/Users/lumisota/.local/share/virtualenvs/ietfdata-T4daMdMS/lib/python3.7/site-packages/datafiles/model.py", line 95, in modified_init
    Model.__post_init__(self)
  File "/Users/lumisota/.local/share/virtualenvs/ietfdata-T4daMdMS/lib/python3.7/site-packages/datafiles/model.py", line 32, in __post_init__
    self.datafile.load(_first_load=True)
  File "/Users/lumisota/.local/share/virtualenvs/ietfdata-T4daMdMS/lib/python3.7/site-packages/datafiles/mapper.py", line 206, in load
    self._set_value(self._instance, name, converter, data, _first_load)
  File "/Users/lumisota/.local/share/virtualenvs/ietfdata-T4daMdMS/lib/python3.7/site-packages/datafiles/mapper.py", line 266, in _set_value
    value = converter.to_python_value(file_value, target_object=init_value)
  File "/Users/lumisota/.local/share/virtualenvs/ietfdata-T4daMdMS/lib/python3.7/site-packages/datafiles/converters/containers.py", line 166, in to_python_value
    value.__dict__ = new_value.__dict__
AttributeError: attribute '__dict__' of 'type' objects is not writable
```

**Comment by jacebrowning** [comment]
Thanks for the clear bug report! This should be fixed now: https://pypi.org/project/datafiles/0.8.1/
