### ISSUE TITLE
Incorrect serialisation of optional nested dataclasses

### ISSUE THREAD

**Issue by lumisota** [jacebrowning/datafiles#165]
The following code:

```
from datafiles   import datafile
from dataclasses import dataclass
from typing      import Optional

@dataclass
class Name:
    value : str

@datafile("samples/{self.key}.yml")
@dataclass
class Sample:

    key: int
    name: Optional[Name]
    value: float = 0.0
    
sample = Sample(42, None)
```

results in the following YAML output in ```samples/42.yml```:

```
name:
  value: ''
```

This doesn't capture the constructed Sample object, where name is None.

**Comment by jacebrowning** [comment]
The fix for this should be available in the next release or you can install a beta: https://pypi.org/project/datafiles/0.9b1/

**Comment by lumisota** [comment]
Thanks; I think this fixes the serialisation. However, when I try to deserialise with:

```
sample2 = Sample.objects.get(42, Missing)
```

I get an exception:

```
INFO: datafiles.mapper: Loading 'Sample' object from 'samples/42.json'
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1003, in fields
    fields = getattr(class_or_instance, _FIELDS)
AttributeError: type object '_MISSING_TYPE' has no attribute '__dataclass_fields__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    sample2 = Sample.objects.get(42, Missing)
  File "/Users/lumisota/.local/share/virtualenvs/ietfdata-T4daMdMS/lib/python3.7/site-packages/datafiles/manager.py", line 46, in get
    instance.datafile.load()
  File "/Users/lumisota/.local/share/virtualenvs/ietfdata-T4daMdMS/lib/python3.7/site-packages/datafiles/mapper.py", line 198, in load
    self._set_value(self._instance, name, converter, data, _first_load)
  File "/Users/lumisota/.local/share/virtualenvs/ietfdata-T4daMdMS/lib/python3.7/site-packages/datafiles/mapper.py", line 258, in _set_value
    value = converter.to_python_value(file_value, target_object=init_value)
  File "/Users/lumisota/.local/share/virtualenvs/ietfdata-T4daMdMS/lib/python3.7/site-packages/datafiles/converters/containers.py", line 154, in to_python_value
    converted = get_default_field_value(target_object, name)
  File "/Users/lumisota/.local/share/virtualenvs/ietfdata-T4daMdMS/lib/python3.7/site-packages/datafiles/utils.py", line 22, in get_default_field_value
    for field in dataclasses.fields(instance):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1005, in fields
    raise TypeError('must be called with a dataclass type or instance')
TypeError: must be called with a dataclass type or instance
```

**Comment by jacebrowning** [comment]
That's probably a separate issue. Would you mind submitting a new bug report for that?
