### ISSUE TITLE
`Optional[Enums]` don't work when they are None.

### ISSUE THREAD

**Issue by svirpridon** [jacebrowning/datafiles#194]
Hi, I found a bug related to optional. Here's an example with enums:

```
from enum import Enum
from typing import Optional

from datafiles import datafile

class Color(Enum):
    RED = 1
    GREEN = 2
    BLUE = 3

@datafile("favorite_color_{self.name}.yaml")
class FavoriteColor:
    name: str
    color: Optional[Color] = None

for entry in [FavoriteColor("Jim", Color.RED), FavoriteColor("Bob", None)]:
    print(f"Created: {entry}")
    print(f"Loading via name: {FavoriteColor(entry.name)}")
```

Leads to:

```
$ python3 fail.py
Created: FavoriteColor(name='Jim', color=<Color.RED: 1>)
Loading via name: FavoriteColor(name='Jim', color=<Color.RED: 1>)
Created: FavoriteColor(name='Bob', color=None)
ValueError: None is not a valid Color

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fail.py", line 18, in <module>
    print(f"Loading via name: {FavoriteColor(entry.name)}")
  File "/home/jonathanbooth/.pyenv/versions/3.7.3/lib/python3.7/site-packages/datafiles/model.py", line 95, in modified_init
    Model.__post_init__(self)
  File "/home/jonathanbooth/.pyenv/versions/3.7.3/lib/python3.7/site-packages/datafiles/model.py", line 32, in __post_init__
    self.datafile.load(_first_load=True)
  File "/home/jonathanbooth/.pyenv/versions/3.7.3/lib/python3.7/site-packages/datafiles/mapper.py", line 193, in load
    self._set_value(self._instance, name, converter, data, _first_load)
  File "/home/jonathanbooth/.pyenv/versions/3.7.3/lib/python3.7/site-packages/datafiles/mapper.py", line 250, in _set_value
    default_value, target_object=init_value
  File "/home/jonathanbooth/.pyenv/versions/3.7.3/lib/python3.7/site-packages/datafiles/converters/enumerations.py", line 19, in to_python_value
    return cls.ENUM(deserialized_data)
  File "/home/jonathanbooth/.pyenv/versions/3.7.3/lib/python3.7/enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "/home/jonathanbooth/.pyenv/versions/3.7.3/lib/python3.7/enum.py", line 564, in __new__
    raise exc
  File "/home/jonathanbooth/.pyenv/versions/3.7.3/lib/python3.7/enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "/home/jonathanbooth/.pyenv/versions/3.7.3/lib/python3.7/enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: None is not a valid Color
```

Testing with `Optional[date]` using the documented date converter suggests this problem extends more broadly. I suspect the correct fix is probably in Converter.as_optional:

```
    @classmethod
    def as_optional(cls):
        class Optional:
            @classmethod
            def to_python_value(cls, deserialized_data, *, target_object=None):
                if cls.DEFAULT is None and deserialized_data is None:
                    return None

                return super().to_python_value(deserialized_data, target_object=target_object)

        name = 'Optional' + cls.__name__
        bases = (Optional, cls)
        attributes = {'DEFAULT': None}
        return type(name, bases, attributes)
```

If that is the correct fix, I think Converter's other `cls.DEFAULT` interaction should probably migrate up into `class Optional` as well?

**Comment by jacebrowning** [comment]
Thanks for the clear bug report! I've reproduced this with these [failing tests](https://github.com/jacebrowning/datafiles/commit/418113dba98787658eef56c9eb8750a7fab36ec4).

Your proposed fix looks promising. I'll try to work on this in the next few days. Feel free to submit a PR!

**Comment by jacebrowning** [comment]
This should be fixed in this release: https://pypi.org/project/datafiles/0.12b3/
