### ISSUE TITLE
Handling of optional attributes should be consistent in nested dataclasses

### ISSUE THREAD

**Issue by tbabej** [jacebrowning/datafiles#219]
If I define a datafile class that has an optional attribute,

```python
@datafile("test.yml")
class Person:
    name: str
    weight: Optional[int]
```

a key corresponding to that attribute can be completely missing from the corresponding `yml` datafile:

```yaml
# contents of test.yml
name: John Doe
```

and the default (None) value is filled in:
```python
>>> list(Person.objects.all())
[Person(name='John Doe', weight=None)]
```

However, if the datafile class has a nested dataclass with an optional attribute

```python
@dataclass
class Attributes:
    mandatory: str
    optional: Optional[str]

@datafile("test.yml")
class Person:
    name: str
    attrs: Attributes
```

the case when the nested object's representation has the optional attribute explicitly stated (even if empty),

```yaml
name: John Doe
attrs:
  mandatory: must be here
  optional:
```

works as expected,

```python
>>> list(Person.objects.all())
[Person(name='John Doe', attrs=Attributes(mandatory='must be here', optional=None))]
```

but, if the `optional:` key is missing from the `yml` file altogether

```yaml
name: John Doe
attrs:
  mandatory: must be here
```

the same code path results in the following traceback

```python
>>> list(Person.objects.all())
Traceback (most recent call last):
  File "/usr/lib64/python3.9/dataclasses.py", line 1033, in fields
    fields = getattr(class_or_instance, _FIELDS)
AttributeError: type object '_MISSING_TYPE' has no attribute '__dataclass_fields__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tbabej/Temp/datafiles_bug/t.py", line 18, in <module>
    print(list(Person.objects.all()))
  File "/home/tbabej/Temp/datafiles_bug/lib64/python3.9/site-packages/datafiles/manager.py", line 104, in all
    yield self.get(*values)
  File "/home/tbabej/Temp/datafiles_bug/lib64/python3.9/site-packages/datafiles/manager.py", line 47, in get
    instance.datafile.load()
  File "/home/tbabej/Temp/datafiles_bug/lib64/python3.9/site-packages/datafiles/mapper.py", line 193, in load
    self._set_value(self._instance, name, converter, data, _first_load)
  File "/home/tbabej/Temp/datafiles_bug/lib64/python3.9/site-packages/datafiles/mapper.py", line 253, in _set_value
    value = converter.to_python_value(file_value, target_object=init_value)
  File "/home/tbabej/Temp/datafiles_bug/lib64/python3.9/site-packages/datafiles/converters/containers.py", line 200, in to_python_value
    converted = get_default_field_value(target_object, name)
  File "/home/tbabej/Temp/datafiles_bug/lib64/python3.9/site-packages/datafiles/utils.py", line 22, in get_default_field_value
    for field in dataclasses.fields(instance):
  File "/usr/lib64/python3.9/dataclasses.py", line 1035, in fields
    raise TypeError('must be called with a dataclass type or instance')
TypeError: must be called with a dataclass type or instance
```

**Comment by jacebrowning** [comment]
Thanks for the clear bug report! I think I've seen this myself, but was not quite sure how to reproduce it.

**Comment by jacebrowning** [comment]
This should be fixed here: https://pypi.org/project/datafiles/0.13.2/

Please let me know if you run into any more issues!

**Comment by tbabej** [comment]
I can confirm `0.13.2` indeed fixes the issue. Thanks for the quick fix!
